
USE Bodega_DSP;


CREATE TABLE EMPLEADO
(
ID_EMPLEADO INT PRIMARY KEY IDENTITY,
USUARIO VARCHAR(15) UNIQUE NOT NULL,
PASSWORD VARCHAR(100) NOT NULL
);

CREATE TABLE DETALLE_EMPLEADO
(
ID_DETALLE INT PRIMARY KEY IDENTITY,
NOMBRE VARCHAR(100) NOT NULL,
APELLIDO VARCHAR(100) NOT NULL,
DUI VARCHAR(9) UNIQUE NOT NULL, 
TELEFONO VARCHAR(8)UNIQUE NOT NULL,
CORREO VARCHAR(255)  UNIQUE NOT NULL,
FECHA_REGISTRO DATE NOT NULL,
ID_EMPLEADO INT UNIQUE NOT NULL,
CONSTRAINT fk_empleado_detalle
FOREIGN KEY(ID_EMPLEADO) REFERENCES EMPLEADO (ID_EMPLEADO) 
);

CREATE TABLE ROL
(
ID_ROL INT PRIMARY KEY IDENTITY,
NOMBRE VARCHAR(100) NOT NULL,
DESCRIPCION VARCHAR(255) NOT NULL
);

CREATE TABLE USER_ROL
(
	ID_ASIGNACION INT PRIMARY KEY IDENTITY,
	ID_EMPLEADO  INT UNIQUE NOT NULL,
	ID_ROL INT NOT NULL,
	CONSTRAINT fk_empleado_rol
	FOREIGN KEY(ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO),
	CONSTRAINT fk_rol 
	FOREIGN KEY(ID_ROL) REFERENCES ROL(ID_ROL)
);


CREATE TABLE PROVEEDOR(
ID_PROVEEDOR INT PRIMARY KEY IDENTITY,
NOMBRE VARCHAR(100) NOT NULL,
APELLIDO VARCHAR(100) NOT NULL,
CORREO VARCHAR(100) UNIQUE NOT NULL,
TELEFONO VARCHAR(8) UNIQUE NOT NULL
);


CREATE TABLE LOTE(
ID_LOTE INT PRIMARY KEY IDENTITY,
NUM_SERIE INT UNIQUE NOT NULL,
FECHA_PRODUCCION DATE NOT NULL,
FECHA_INGRESO DATE NOT NULL,
PRECIO DECIMAL(10,2) NOT NULL,
ID_PROVEEDOR INT NOT NULL,
CONSTRAINT fk_proveedor_lote
FOREIGN KEY(ID_PROVEEDOR) REFERENCES PROVEEDOR(ID_PROVEEDOR)
);


CREATE TABLE CATEGORIA_PERECEDERO(
ID_PERECEDERO INT PRIMARY KEY IDENTITY,
NOMBRE  VARCHAR(100) UNIQUE NOT NULL,
DESCRIPCION VARCHAR(255) NOT NULL
);

CREATE TABLE  CATEGORIA_PRODUCTO(
ID_CATEGORIA INT PRIMARY KEY IDENTITY,
NOMBRE VARCHAR(100) UNIQUE NOT NULL,
DESCRIPCION VARCHAR(255) NOT NULL,
ID_PERECEDERO INT NOT NULL,
CONSTRAINT fk_perecedero_categoria
FOREIGN KEY (ID_PERECEDERO) REFERENCES CATEGORIA_PERECEDERO(ID_PERECEDERO)

);


CREATE TABLE PRODUCTO(
ID_PRODUCTO INT PRIMARY KEY IDENTITY,
SERIE_LOTE INT NOT NULL,
CATEGORIA_PRODUCTO INT NOT NULL,
CONSTRAINT fk_Lote_producto
FOREIGN KEY (SERIE_LOTE) REFERENCES LOTE(ID_LOTE),
CONSTRAINT fk_categoria_producto
FOREIGN KEY (CATEGORIA_PRODUCTO) REFERENCES CATEGORIA_PRODUCTO(ID_CATEGORIA)
);



CREATE TABLE DETALLE_PRODUCTO(
ID_DETALLE INT PRIMARY KEY IDENTITY,
ID_PRODUCTO INT UNIQUE NOT NULL,
NOMBRE VARCHAR(200) NOT NULL,
FECHA_CADUCIDAD DATE NULL,
DESCRIPCION VARCHAR(200) NOT NULL
CONSTRAINT fk_Detalle_producto
FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO)
);


CREATE TABLE CATEGORIA_PASILLO(
ID_CATEGORIA INT PRIMARY KEY IDENTITY,
NOMBRE VARCHAR(10) UNIQUE NOT NULL,
DESCRIPCION VARCHAR(200) NOT NULL
);

CREATE TABLE PASILLO(
ID_PASILLO INT PRIMARY KEY IDENTITY,
ID_CATEGORIA INT NOT NULL,
CONSTRAINT fk_categoria_pasillo
FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA_PASILLO(ID_CATEGORIA)
);


CREATE TABLE STOCK_PRODUCTO(
ID_STOCK INT PRIMARY KEY IDENTITY,
SKU VARCHAR(8) UNIQUE NOT NULL,
ID_PRODUCTO INT NOT NULL,
ID_PASILLO INT UNIQUE NOT NULL,
CONSTRAINT fk_producto_stock
FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO),
CONSTRAINT fk_pasillo_producto
FOREIGN KEY (ID_PASILLO) REFERENCES PASILLO(ID_PASILLO)
);